#!/usr/bin/env python3
"""
Rule-Based Fraud Detection System for Social Media Platform
Detects suspicious reviews, fake accounts, and coordinated attacks
"""

import re
import json
from datetime import datetime, timedelta
from typing import List, Dict, Any, Tuple
from collections import defaultdict, Counter
import hashlib
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class FraudDetectionEngine:
    def __init__(self):
        """Initialize the fraud detection engine with configurable thresholds"""
        
        # Configurable thresholds
        self.config = {
            # Text-based rules
            'min_review_length': 10,
            'max_review_length': 5000,
            'max_repeated_chars': 5,
            'max_caps_percentage': 0.7,
            'suspicious_word_threshold': 3,
            
            # User behavior rules
            'max_reviews_per_day': 20,
            'max_reviews_per_hour': 5,
            'min_account_age_days': 1,
            'velocity_window_hours': 24,
            
            # Pattern detection
            'similarity_threshold': 0.85,
            'coordinated_attack_threshold': 5,
            'rating_manipulation_threshold': 0.8,
            
            # Time-based rules
            'off_hours_weight': 1.5,
            'weekend_weight': 1.2,
        }
        
        # Suspicious patterns
        self.suspicious_words = {
            'fake_positive': [
                'best ever', 'amazing product', 'highly recommend', 'perfect item',
                'five stars', '5 stars', 'great quality', 'fast shipping',
                'excellent service', 'worth every penny'
            ],
            'fake_negative': [
                'worst ever', 'terrible product', 'complete waste', 'dont buy',
                'scam', 'fraud', 'fake item', 'poor quality'
            ],
            'spam_indicators': [
                'click here', 'visit my', 'check out', 'follow me',
                'dm me', 'contact me', 'buy from', 'cheap price'
            ]
        }
        
        # Common bot patterns
        self.bot_patterns = [
            r'\b(bot|robot|automated|script)\b',
            r'generated by|created by|powered by',
            r'copy.*paste|ctrl.*c|ctrl.*v',
        ]
        
        # Store for pattern analysis
        self.user_history = defaultdict(list)
        self.review_fingerprints = defaultdict(list)
        self.ip_history = defaultdict(list)
    
    def calculate_risk_score(self, review_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Calculate overall fraud risk score for a review
        
        Args:
            review_data: Dictionary containing review information
                Required keys: text, user_id, rating, timestamp
                Optional keys: ip_address, user_agent, account_created, device_info
        
        Returns:
            Dictionary with risk assessment
        """
        risk_factors = []
        total_risk_score = 0.0
        
        # Text-based analysis
        text_risks = self._analyze_text_patterns(review_data.get('text', ''))
        risk_factors.extend(text_risks['risks'])
        total_risk_score += text_risks['score']
        
        # User behavior analysis
        user_risks = self._analyze_user_behavior(review_data)
        risk_factors.extend(user_risks['risks'])
        total_risk_score += user_risks['score']
        
        # Rating manipulation detection
        rating_risks = self._analyze_rating_patterns(review_data)
        risk_factors.extend(rating_risks['risks'])
        total_risk_score += rating_risks['score']
        
        # Temporal analysis
        time_risks = self._analyze_temporal_patterns(review_data)
        risk_factors.extend(time_risks['risks'])
        total_risk_score += time_risks['score']
        
        # Technical fingerprinting
        tech_risks = self._analyze_technical_patterns(review_data)
        risk_factors.extend(tech_risks['risks'])
        total_risk_score += tech_risks['score']
        
        # Determine risk level
        risk_level = self._calculate_risk_level(total_risk_score)
        
        # Store data for future pattern analysis
        self._update_history(review_data)
        
        return {
            'risk_score': round(total_risk_score, 2),
            'risk_level': risk_level,
            'risk_factors': risk_factors,
            'recommendations': self._get_recommendations(risk_level, risk_factors),
            'timestamp': datetime.now().isoformat()
        }
    
    def _analyze_text_patterns(self, text: str) -> Dict[str, Any]:
        """Analyze text for suspicious patterns"""
        risks = []
        score = 0.0
        
        if not text:
            risks.append("Empty review text")
            score += 30.0
            return {'risks': risks, 'score': score}
        
        # Length checks
        if len(text) < self.config['min_review_length']:
            risks.append(f"Very short review ({len(text)} chars)")
            score += 15.0
        elif len(text) > self.config['max_review_length']:
            risks.append(f"Unusually long review ({len(text)} chars)")
            score += 10.0
        
        # Repetitive characters
        repeated_chars = max(len(match.group()) for match in re.finditer(r'(.)\1*', text))
        if repeated_chars > self.config['max_repeated_chars']:
            risks.append(f"Excessive repeated characters ({repeated_chars})")
            score += 20.0
        
        # Excessive caps
        caps_ratio = sum(1 for c in text if c.isupper()) / len(text) if text else 0
        if caps_ratio > self.config['max_caps_percentage']:
            risks.append(f"Excessive capital letters ({caps_ratio:.1%})")
            score += 15.0
        
        # Suspicious word detection
        text_lower = text.lower()
        suspicious_count = 0
        
        for category, words in self.suspicious_words.items():
            found_words = [word for word in words if word in text_lower]
            if found_words:
                suspicious_count += len(found_words)
                risks.append(f"Contains {category} keywords: {', '.join(found_words[:3])}")
        
        if suspicious_count > self.config['suspicious_word_threshold']:
            score += min(suspicious_count * 5, 25.0)
        
        # Bot pattern detection
        for pattern in self.bot_patterns:
            if re.search(pattern, text_lower):
                risks.append("Contains bot-like patterns")
                score += 25.0
                break
        
        # Generic/template detection
        if self._is_generic_text(text):
            risks.append("Generic/template-like content")
            score += 20.0
        
        return {'risks': risks, 'score': score}
    
    def _analyze_user_behavior(self, review_data: Dict[str, Any]) -> Dict[str, Any]:
        """Analyze user behavior patterns"""
        risks = []
        score = 0.0
        
        user_id = review_data.get('user_id')
        if not user_id:
            risks.append("Missing user ID")
            score += 50.0
            return {'risks': risks, 'score': score}
        
        # Account age check
        account_created = review_data.get('account_created')
        if account_created:
            account_age = (datetime.now() - datetime.fromisoformat(account_created)).days
            if account_age < self.config['min_account_age_days']:
                risks.append(f"Very new account ({account_age} days old)")
                score += 25.0
        
        # Review velocity check
        user_reviews = self.user_history[user_id]
        now = datetime.now()
        
        # Daily review count
        today_reviews = [r for r in user_reviews 
                        if (now - datetime.fromisoformat(r['timestamp'])).days == 0]
        if len(today_reviews) > self.config['max_reviews_per_day']:
            risks.append(f"Too many reviews today ({len(today_reviews)})")
            score += 30.0
        
        # Hourly review count
        recent_reviews = [r for r in user_reviews 
                         if (now - datetime.fromisoformat(r['timestamp'])).seconds < 3600]
        if len(recent_reviews) > self.config['max_reviews_per_hour']:
            risks.append(f"Too many reviews this hour ({len(recent_reviews)})")
            score += 35.0
        
        # Review pattern consistency
        if len(user_reviews) > 5:
            ratings = [r.get('rating', 0) for r in user_reviews[-10:]]
            if len(set(ratings)) == 1:  # All same rating
                risks.append("Always gives same rating")
                score += 20.0
        
        return {'risks': risks, 'score': score}
    
    def _analyze_rating_patterns(self, review_data: Dict[str, Any]) -> Dict[str, Any]:
        """Analyze rating manipulation patterns"""
        risks = []
        score = 0.0
        
        rating = review_data.get('rating')
        text = review_data.get('text', '').lower()
        
        if rating is None:
            return {'risks': risks, 'score': score}
        
        # Rating-text mismatch detection
        positive_indicators = sum(1 for word in self.suspicious_words['fake_positive'] 
                                 if word in text)
        negative_indicators = sum(1 for word in self.suspicious_words['fake_negative'] 
                                 if word in text)
        
        # High rating with negative language
        if rating >= 4 and negative_indicators > positive_indicators:
            risks.append("High rating with negative language")
            score += 25.0
        
        # Low rating with positive language
        elif rating <= 2 and positive_indicators > negative_indicators:
            risks.append("Low rating with positive language")
            score += 25.0
        
        # Extreme ratings (1 or 5 stars) are more suspicious
        if rating in [1, 5]:
            score += 5.0
        
        return {'risks': risks, 'score': score}
    
    def _analyze_temporal_patterns(self, review_data: Dict[str, Any]) -> Dict[str, Any]:
        """Analyze timing patterns"""
        risks = []
        score = 0.0
        
        timestamp_str = review_data.get('timestamp')
        if not timestamp_str:
            return {'risks': risks, 'score': score}
        
        try:
            timestamp = datetime.fromisoformat(timestamp_str)
        except:
            risks.append("Invalid timestamp format")
            score += 10.0
            return {'risks': risks, 'score': score}
        
        # Off-hours posting (2 AM - 6 AM local time)
        hour = timestamp.hour
        if 2 <= hour <= 6:
            risks.append("Posted during off-hours")
            score += 10.0
        
        # Weekend pattern (less suspicious but worth noting)
        if timestamp.weekday() >= 5:  # Saturday = 5, Sunday = 6
            score += 2.0
        
        return {'risks': risks, 'score': score}
    
    def _analyze_technical_patterns(self, review_data: Dict[str, Any]) -> Dict[str, Any]:
        """Analyze technical fingerprints"""
        risks = []
        score = 0.0
        
        # IP address analysis
        ip_address = review_data.get('ip_address')
        if ip_address:
            ip_reviews = self.ip_history[ip_address]
            if len(ip_reviews) > 10:  # Too many reviews from same IP
                risks.append(f"Many reviews from same IP ({len(ip_reviews)})")
                score += 25.0
        
        # User agent analysis
        user_agent = review_data.get('user_agent', '').lower()
        if user_agent:
            if 'bot' in user_agent or 'crawler' in user_agent:
                risks.append("Bot-like user agent")
                score += 40.0
            elif not any(browser in user_agent for browser in ['chrome', 'firefox', 'safari', 'edge']):
                risks.append("Unusual user agent")
                score += 15.0
        
        # Device fingerprint consistency
        device_info = review_data.get('device_info', {})
        if device_info and self._is_suspicious_device(device_info):
            risks.append("Suspicious device fingerprint")
            score += 20.0
        
        return {'risks': risks, 'score': score}
    
    def _is_generic_text(self, text: str) -> bool:
        """Check if text appears generic or template-like"""
        # Simple heuristics for generic content
        generic_patterns = [
            r'^(great|good|nice|ok|okay) (product|item|service)',
            r'^(love|like) (it|this|the)',
            r'^(recommend|recommended)',
            r'^(fast|quick) (delivery|shipping)',
        ]
        
        text_lower = text.lower().strip()
        return any(re.match(pattern, text_lower) for pattern in generic_patterns)
    
    def _is_suspicious_device(self, device_info: Dict[str, Any]) -> bool:
        """Check for suspicious device patterns"""
        # Look for automated/headless browser indicators
        screen_res = device_info.get('screen_resolution', '')
        if screen_res in ['1x1', '0x0']:
            return True
        
        # Check for missing standard properties
        required_props = ['screen_resolution', 'timezone', 'language']
        missing_props = sum(1 for prop in required_props if not device_info.get(prop))
        
        return missing_props >= 2
    
    def _calculate_risk_level(self, score: float) -> str:
        """Convert numeric score to risk level"""
        if score >= 70:
            return 'HIGH'
        elif score >= 40:
            return 'MEDIUM'
        elif score >= 20:
            return 'LOW'
        else:
            return 'MINIMAL'
    
    def _get_recommendations(self, risk_level: str, risk_factors: List[str]) -> List[str]:
        """Get action recommendations based on risk assessment"""
        recommendations = []
        
        if risk_level == 'HIGH':
            recommendations.extend([
                "Block review immediately",
                "Flag user account for manual review",
                "Consider temporary account suspension",
                "Investigate for coordinated attack"
            ])
        elif risk_level == 'MEDIUM':
            recommendations.extend([
                "Hold review for manual approval",
                "Increase monitoring on user account",
                "Require additional verification"
            ])
        elif risk_level == 'LOW':
            recommendations.extend([
                "Allow review but monitor closely",
                "Add to watchlist for pattern detection"
            ])
        else:
            recommendations.append("Allow review normally")
        
        # Specific recommendations based on risk factors
        if any('same IP' in factor for factor in risk_factors):
            recommendations.append("Investigate IP address for multiple accounts")
        
        if any('bot' in factor.lower() for factor in risk_factors):
            recommendations.append("Implement CAPTCHA verification")
        
        if any('velocity' in factor or 'many reviews' in factor for factor in risk_factors):
            recommendations.append("Implement rate limiting")
        
        return recommendations
    
    def _update_history(self, review_data: Dict[str, Any]) -> None:
        """Update historical data for pattern analysis"""
        user_id = review_data.get('user_id')
        ip_address = review_data.get('ip_address')
        
        if user_id:
            self.user_history[user_id].append({
                'timestamp': review_data.get('timestamp', datetime.now().isoformat()),
                'rating': review_data.get('rating'),
                'text_length': len(review_data.get('text', ''))
            })
            
            # Keep only recent history (last 100 reviews per user)
            if len(self.user_history[user_id]) > 100:
                self.user_history[user_id] = self.user_history[user_id][-100:]
        
        if ip_address:
            self.ip_history[ip_address].append({
                'timestamp': review_data.get('timestamp', datetime.now().isoformat()),
                'user_id': user_id
            })
    
    def detect_coordinated_attack(self, reviews: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Detect coordinated fake review attacks
        
        Args:
            reviews: List of recent reviews to analyze
        
        Returns:
            Dictionary with attack detection results
        """
        attack_indicators = []
        attack_score = 0.0
        
        if len(reviews) < 3:
            return {'attack_detected': False, 'score': 0.0, 'indicators': []}
        
        # Time clustering - many reviews in short time
        timestamps = []
        for review in reviews:
            try:
                ts = datetime.fromisoformat(review.get('timestamp', ''))
                timestamps.append(ts)
            except:
                continue
        
        if timestamps:
            timestamps.sort()
            time_diffs = [(timestamps[i] - timestamps[i-1]).total_seconds() / 60 
                         for i in range(1, len(timestamps))]
            
            # Check for burst activity
            short_intervals = [diff for diff in time_diffs if diff < 30]  # 30 minutes
            if len(short_intervals) > len(reviews) * 0.5:
                attack_indicators.append(f"Burst activity: {len(short_intervals)} reviews in 30min windows")
                attack_score += 30.0
        
        # Rating clustering - all similar ratings
        ratings = [r.get('rating') for r in reviews if r.get('rating')]
        if ratings:
            rating_variance = len(set(ratings)) / len(ratings)
            if rating_variance < 0.3:  # Low variance
                attack_indicators.append("Suspiciously similar ratings")
                attack_score += 25.0
        
        # Text similarity clustering
        texts = [r.get('text', '') for r in reviews]
        similar_pairs = 0
        
        for i in range(len(texts)):
            for j in range(i + 1, len(texts)):
                if self._calculate_text_similarity(texts[i], texts[j]) > 0.7:
                    similar_pairs += 1
        
        if similar_pairs > len(reviews) * 0.3:
            attack_indicators.append(f"High text similarity: {similar_pairs} similar pairs")
            attack_score += 35.0
        
        # IP clustering
        ips = [r.get('ip_address') for r in reviews if r.get('ip_address')]
        if ips:
            unique_ips = len(set(ips))
            ip_diversity = unique_ips / len(ips)
            if ip_diversity < 0.5:
                attack_indicators.append(f"Low IP diversity: {unique_ips} IPs for {len(ips)} reviews")
                attack_score += 20.0
        
        attack_detected = attack_score >= 50.0
        
        return {
            'attack_detected': attack_detected,
            'attack_score': round(attack_score, 2),
            'indicators': attack_indicators,
            'affected_reviews': len(reviews),
            'recommendation': 'Block all reviews and investigate accounts' if attack_detected else 'Continue monitoring'
        }
    
    def _calculate_text_similarity(self, text1: str, text2: str) -> float:
        """Calculate simple text similarity using word overlap"""
        if not text1 or not text2:
            return 0.0
        
        words1 = set(text1.lower().split())
        words2 = set(text2.lower().split())
        
        if not words1 or not words2:
            return 0.0
        
        intersection = words1.intersection(words2)
        union = words1.union(words2)
        
        return len(intersection) / len(union)

def main():
    """Example usage of the fraud detection system"""
    print("=== Rule-Based Fraud Detection System ===\n")
    
    # Initialize detector
    detector = FraudDetectionEngine()
    
    # Example review data
    sample_reviews = [
        {
            'text': 'This product is amazing! Best purchase ever! Highly recommend! Five stars!',
            'user_id': 'user123',
            'rating': 5,
            'timestamp': datetime.now().isoformat(),
            'ip_address': '192.168.1.1',
            'user_agent': 'Mozilla/5.0 (compatible; Bot/1.0)',
            'account_created': (datetime.now() - timedelta(days=1)).isoformat()
        },
        {
            'text': 'Good product, works as expected. Fair price.',
            'user_id': 'user456',
            'rating': 4,
            'timestamp': datetime.now().isoformat(),
            'ip_address': '192.168.1.2',
            'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
            'account_created': (datetime.now() - timedelta(days=30)).isoformat()
        },
        {
            'text': 'TERRIBLE!!!!! WORST PRODUCT EVER!!!! DONT BUY!!!!',
            'user_id': 'user789',
            'rating': 1,
            'timestamp': datetime.now().isoformat(),
            'ip_address': '192.168.1.1',  # Same IP as first review
            'account_created': (datetime.now() - timedelta(hours=2)).isoformat()
        }
    ]
    
    print("=== Individual Review Analysis ===\n")
    
    for i, review in enumerate(sample_reviews, 1):
        print(f"--- Review {i} ---")
        print(f"Text: {review['text'][:80]}...")
        print(f"Rating: {review['rating']}/5")
        print(f"User: {review['user_id']}")
        
        # Analyze fraud risk
        result = detector.calculate_risk_score(review)
        
        print(f"Risk Level: {result['risk_level']}")
        print(f"Risk Score: {result['risk_score']}/100")
        
        if result['risk_factors']:
            print("Risk Factors:")
            for factor in result['risk_factors']:
                print(f"  - {factor}")
        
        if result['recommendations']:
            print("Recommendations:")
            for rec in result['recommendations']:
                print(f"  • {rec}")
        
        print()
    
    print("=== Coordinated Attack Detection ===\n")
    
    # Test coordinated attack detection
    attack_result = detector.detect_coordinated_attack(sample_reviews)
    
    print(f"Attack Detected: {attack_result['attack_detected']}")
    print(f"Attack Score: {attack_result['attack_score']}/100")
    
    if attack_result['indicators']:
        print("Attack Indicators:")
        for indicator in attack_result['indicators']:
            print(f"  - {indicator}")
    
    print(f"Recommendation: {attack_result['recommendation']}")
    
    # Save results
    results = {
        'individual_analyses': [detector.calculate_risk_score(review) for review in sample_reviews],
        'coordinated_attack_analysis': attack_result,
        'timestamp': datetime.now().isoformat()
    }
    
    filename = f"fraud_detection_results_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(filename, 'w') as f:
        json.dump(results, f, indent=2)
    
    print(f"\nResults saved to: {filename}")

if __name__ == "__main__":
    main()